# SITE CONFIGURATION
title: Photography and DIY projects # your site title
author: JM Torrente # You :P
description: > # Meta description of Homepage
  This is the place for those weak of mind, those who forget everything they do and need a place to store it.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jmtorrente.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: JM Torrente 
  links:
    #- https://twitter.com/BenBalter
    #- https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/jos%C3%A9-manuel-torrente-delgado-756518ab/
    #- https://plus.google.com/+BenBalter
    - https://github.com/jmtorrente
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Gallery', link: '/gallery'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Film and Digital Photography met with technology

hero_img: posts/RiaÃ±o Siglo XX 1.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: jmtorrented@gmail.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  jmtorrente # replace with your_github_username or comment to remove link from footer
instagram_username: chema_chemos # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: josmanueltorrente # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-PG3Z5S3 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or null or pygments
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
